version: '3'
 
services:
  db:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "3306:3306"
    volumes:
      - dbdatapetshop:/var/lib/mysql
volumes:
  dbdatapetshop: